export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_PROJECT_BEGIN = 'ADD_PROJECT_BEGIN';
export const ADD_RPOJECT_ERROR = 'ADD_RPOJECT_ERROR';
export const LOAD_RPOJECT = 'LOAD_RPOJECT';
export const LOAD_RPOJECT_SUCCESS = 'LOAD_RPOJECT_SUCCESS';
export const LOAD_RPOJECT_ERROR = 'LOAD_RPOJECT_ERROR';
